AWSTemplateFormatVersion: '2010-09-09'

Description: "Constructs the lambda, with appropriate permissions, which generates
  the unified Timeseries Historical bandwidth, buoy weather data per spot-beam 
  for usage with SageMaker Autopilot Timeseries.
  Puts results in S3 bucket.  
  Prerequisites - zip up the lambda_function and place in S3Bucket/prefix"

# parameters to pass to the CFN
Parameters:

    SatComDatasetS3Bucket:
        Type: String
        Description: Bucket for all of the satcom-forecast SageMaker Autopilot assets
        Default: "forecast-satcom-autopilot-capacity"
        
    SatComGenLambdaZipName:
        Type: String
        Description: Name of the lambda zip file generating complete dataset (target, covariates etc)
        Default: "datagen-fxns/satcom-timeseries-datagen-fxn.zip"
        
        
# creation of AWS resources        
Resources:

  ProcessLambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonS3FullAccess

  # Note - the Env Vars csv file names are simply used as prefixes - the Lambda will generate unique filenames
  ProcessLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function to generate unified csv data for Sat Cap SageMaker Autopilot timeseries
      Handler: lambda_function.lambda_handler
      Timeout: 60
      Role: !GetAtt ProcessLambdaFunctionExecutionRole.Arn
      Code:
        S3Bucket: !Ref SatComDatasetS3Bucket
        S3Key: !Ref SatComGenLambdaZipName
      Runtime: python3.12
      Environment:
        Variables:
          bucketName: !Ref SatComDatasetS3Bucket
          timeseriesSatCom: satcom-autopilot-cap.csv
          mode: train
      Tags:
      - Key: Name
        Value: !Join [ "-", [ !Ref "AWS::StackName", ProcessLambdaFunction] ]
        

Outputs:
  LambdaFxnName:
    Value: !Ref ProcessLambdaFunction
